#!/usr/bin/env python3


import fullbeamline
import sys


help_message = \
"""fullbeamline --help
    prints this help message

fullbeamline --update
    downloads the latest version of bmad from Cornell's website

fullbeamline --clean
    deletes all compiled files

fullbeamline --build production
fullbeamline --build debug
    compiles bmad

fullbeamline --check
    checks the current installation
"""


def main():
    if (len(sys.argv) < 2):
        print('\033[1mfullbeamline: \033[31merror: \033[0mno command specified')
        sys.exit(1)
    command = sys.argv[1]
    if command == '--help':
        print(help_message)
    elif command == '--callgpt':
        fullbeamline.callgpt()
    elif command == '--update':
        fullbeamline.update()
    elif command == '--clean':
        fullbeamline.clean()
    elif command == '--check':
        print('\033[32mok\033[0m')
    elif command == '--build':
        if len(sys.argv) > 2 and sys.argv[2] == 'debug':
            fullbeamline.build('debug')
        elif len(sys.argv) > 2 and sys.argv[2] == 'production':
            fullbeamline.build('production')
        else:
            print('\033[1mfullbeamline: \033[31merror: \033[0mmust specify \'de'
                  'bug\' or \'production\' after --build')
    else:
        print('\033[1mfullbeamline: \033[31merror: \033[0mcommand \'{}\' not re'
              'cognized'.format(command))


if __name__ == '__main__':
    main()
